# Generated by Django 5.1.1 on 2024-09-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_list_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='item',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
